### ISSUE TITLE
prompt_toolkit not required

### ISSUE THREAD

**Issue by ErikBoesen** [alice1017/SelectMenu#1]
I had to install this manually. Seems like a mistake.

**Comment by ErikBoesen** [comment]
I'm happy to fix this, by the way.

**Comment by alice1017** [comment]
@ErikBoesen Thank you for issue. SelectMenu imports the `prompt_toolkit` here.
https://github.com/alice1017/SelectMenu/blob/master/selectmenu/core.py#L6
What do you mean?

**Comment by ErikBoesen** [comment]
I said the wrong thing. I meant that it doesn't seem to be installed as a dependency.

**Comment by alice1017** [comment]
@ErikBoesen That makes sense. I wrote the **install_require** attribute in `setup.py` here.
https://github.com/alice1017/SelectMenu/blob/master/setup.py#L21

Do you use `setup.py` for install? or another way?
```
$ python setup.py build install
```

If `prompt_toolkit` doesn't install, you can install manually by `pip`.
```
$ pip install -r requirements.txt
```

Please try.

**Comment by ErikBoesen** [comment]
I installed through pip. I already installed prompt-toolkit manually, but I don't think I should have to

**Comment by alice1017** [comment]
@ErikBoesen Good! I will close this issue.
