### ISSUE TITLE
ModuleNotFoundError: No module named 'prompt_toolkit'

### ISSUE THREAD

**Issue by andli** [alice1017/SelectMenu#2]
Hi!

Cannot use pip to install SelectMenu, I think there may be some issue with the dependency to `prompt_toolkit`. 

Python 3.6.5 in a venv.

**Comment by siredmar** [comment]
Same thing here.

**Comment by cztrollolcz** [comment]
Same thing

**Comment by alice1017** [comment]
Please install `prompt_toolkit`.

```
$ cd SelectMenu
$ pip install -r ./requirements.txt
```
